import { create } from 'zustand';

interface LanguageState {
  language: 'fr' | 'en';
  setLanguage: (lang: 'fr' | 'en') => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Header
    'search.placeholder': 'Rechercher un projet, établissement...',
    'notifications': 'Notifications',
    'help': 'Aide',
    'logout': 'Déconnexion',
    
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.projects': 'Mes projets',
    'nav.companies': 'Mes sociétés',
    'nav.newRequest': 'Nouvelle demande',
    'nav.documents': 'Mes documents',
    'nav.compliance': 'Conformité',
    'nav.mairie': 'Interface Mairie',
    'nav.settings': 'Paramètres',
    
    // Dashboard
    'dashboard.welcome': 'Bonjour',
    'dashboard.overview': 'Voici un aperçu de vos projets et échéances',
    'dashboard.activeCompany': 'Société active:',
    'dashboard.totalProjects': 'Total de projets',
    'dashboard.inProgress': 'En cours',
    'dashboard.completed': 'Terminés',
    'dashboard.urgent': 'Urgents',
    'dashboard.recentProjects': 'Projets récents',
    'dashboard.viewAll': 'Voir tous',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.newAT': 'Nouvelle demande AT',
    'dashboard.scheduleAudit': 'Planifier audit',
    'dashboard.complianceTracking': 'Suivi conformité',
    'dashboard.upcomingDeadlines': 'Prochaines échéances',
    'dashboard.noDeadlines': 'Aucune échéance prochaine',
    
    // Settings Page
    'settings.title': 'Paramètres du compte',
    'settings.subtitle': 'Gérez vos informations personnelles et préférences',
    'settings.profile': 'Profil',
    'settings.notifications': 'Notifications',
    'settings.security': 'Sécurité',
    'settings.preferences': 'Préférences',
    'settings.companies': 'Mes sociétés',
    'settings.save': 'Sauvegarder',
    
    // Profile Tab
    'settings.profile.title': 'Informations personnelles',
    'settings.profile.avatar': 'Photo de profil',
    'settings.profile.avatarFormats': 'Formats acceptés : JPG, PNG (max 2MB)',
    'settings.profile.change': 'Changer',
    'settings.profile.remove': 'Supprimer',
    'settings.profile.firstName': 'Prénom',
    'settings.profile.lastName': 'Nom',
    'settings.profile.email': 'Email',
    'settings.profile.phone': 'Téléphone',
    'settings.profile.position': 'Fonction',
    'settings.profile.mainCompany': 'Société principale',
    
    // Notifications Tab
    'settings.notifications.title': 'Préférences de notifications',
    'settings.notifications.email': 'Notifications par email',
    'settings.notifications.sms': 'Notifications par SMS',
    'settings.notifications.whatsapp': 'Notifications WhatsApp',
    'settings.notifications.projectUpdates': 'Mises à jour de projets',
    'settings.notifications.deadlines': 'Rappels d\'échéances',
    'settings.notifications.documents': 'Nouveaux documents',
    'settings.notifications.marketing': 'Actualités Prévéris',
    'settings.notifications.urgent': 'Actions urgentes uniquement',
    'settings.notifications.urgentOnly': 'Actions urgentes',
    
    // Security Tab
    'settings.security.title': 'Sécurité et confidentialité',
    'settings.security.authMethod': 'Méthode d\'authentification',
    'settings.security.secureLogin': 'Connexion par code sécurisée',
    'settings.security.passwordless': 'Votre compte utilise l\'authentification sans mot de passe',
    'settings.security.activeSessions': 'Sessions actives',
    'settings.security.currentSession': 'Session actuelle',
    'settings.security.lastActivity': 'Dernière activité',
    'settings.security.now': 'maintenant',
    'settings.security.hoursAgo': 'il y a 2 heures',
    'settings.security.disconnect': 'Déconnecter',
    'settings.security.disconnectAll': 'Déconnecter toutes les autres sessions',
    'settings.security.dataManagement': 'Gestion des données',
    'settings.security.exportData': 'Exporter mes données',
    'settings.security.dangerZone': 'Zone de danger',
    'settings.security.deleteAccount': 'Supprimer mon compte',
    'settings.security.deleteWarning': 'Cette action est irréversible. Toutes vos données seront définitivement supprimées.',
    'settings.security.active': 'Actif',
    'settings.security.current': 'Actuelle',
    
    // Preferences Tab
    'settings.preferences.title': 'Préférences d\'interface',
    'settings.preferences.language': 'Langue',
    'settings.preferences.theme': 'Thème',
    'settings.preferences.timezone': 'Fuseau horaire',
    'settings.preferences.dateFormat': 'Format de date',
    'settings.preferences.helpLevel': 'Niveau d\'aide',
    'settings.preferences.currency': 'Devise',
    'settings.preferences.advanced': 'Options avancées',
    'settings.preferences.autoSave': 'Sauvegarde automatique des formulaires',
    'settings.preferences.compactMode': 'Mode compact (plus d\'informations par page)',
    'settings.preferences.light': 'Clair',
    'settings.preferences.dark': 'Sombre',
    'settings.preferences.auto': 'Automatique',
    'settings.preferences.beginner': 'Débutant (aide détaillée)',
    'settings.preferences.intermediate': 'Intermédiaire (aide standard)',
    'settings.preferences.expert': 'Expert (aide minimale)',
    
    // Companies Tab
    'settings.companies.title': 'Gestion des accès sociétés',
    'settings.companies.manageAccess': 'Gérer les accès',
    'settings.companies.administrator': 'Administrateur',
    'settings.companies.role': 'Rôle',
    'settings.companies.accessSince': 'Accès depuis',
    'settings.companies.lastConnection': 'Dernière connexion',
    'settings.companies.today': 'Aujourd\'hui',
    'settings.companies.newAccess': 'Accès à une nouvelle société ?',
    'settings.companies.contactAdmin': 'Contactez l\'administrateur de la société ou notre équipe support pour obtenir un accès.',
    'settings.companies.requestAccess': 'Demander un accès',
    
    // Mairie Interface
    'mairie.title': 'Interface Mairie',
    'mairie.subtitle': 'Gestion des instructions ERP pour votre commune',
    'mairie.activePO': 'Bon de commande actif',
    'mairie.budgetUsed': 'Budget consommé',
    'mairie.newPO': 'Nouveau bon de commande',
    'mairie.depositFiles': 'Déposer un dossier ERP pour instruction',
    'mairie.dragDrop': 'Glissez-déposez vos dossiers ici ou cliquez pour sélectionner',
    'mairie.chooseFiles': 'Choisir des fichiers',
    'mairie.instructionTracking': 'Suivi des instructions',
    'mairie.fileNumber': 'N° dossier',
    'mairie.projectAddress': 'Adresse projet',
    'mairie.status': 'Statut',
    'mairie.depositDate': 'Date dépôt',
    'mairie.deadline': 'Échéance',
    'mairie.actions': 'Actions',
    'mairie.downloadAdvice': 'Télécharger avis',
    'mairie.requestReview': 'Demander réétude',
    'mairie.filesProcessed': 'Dossiers instruits ce mois',
    'mairie.avgDelay': 'Délai moyen instruction',
    'mairie.remainingBudget': 'Budget restant',
    'mairie.days': 'jours',
    
    // Status
    'status.complete': 'Complet',
    'status.incomplete': 'Incomplet',
    'status.inProgress': 'En cours',
    'status.inInstruction': 'En instruction',
    'status.validated': 'Validé',
    'status.urgent': 'Urgent',
    'status.finished': 'Terminé',
    
    // Companies
    'companies.title': 'Mes sociétés',
    'companies.subtitle': 'Gérez vos sociétés et établissements',
    'companies.addCompany': 'Ajouter une société',
    'companies.selectCompany': 'Sélectionner une société',
    'companies.establishments': 'Établissements',
    'companies.addEstablishment': 'Ajouter un établissement',
    'companies.listView': 'Liste',
    'companies.mapView': 'Carte',
    'companies.siretValidation': '14 chiffres : 9 chiffres SIREN + 5 chiffres établissement',
    'companies.siretValid': 'SIRET valide',
    'companies.siretInvalid': 'SIRET invalide',
    'companies.siretChecking': 'Vérification en cours...',

    // Auth Page
    'auth.secureTitle': 'Connexion sécurisée',
    'auth.emailLabel': 'Adresse email',
    'auth.emailPlaceholder': 'votre@email.fr',
    'auth.continue': 'Continuer',
    'auth.codeHelp': 'Vous recevrez un code de connexion temporaire',
    'auth.methodTitle': 'Comment souhaitez-vous recevoir votre code ?',
    'auth.back': 'Retour',
    'auth.enterCode': 'Saisissez votre code',
    'auth.codeSentVia': 'Code envoyé via',
    'auth.codePlaceholder': '123456',
    'auth.login': 'Se connecter',
    'auth.loading': 'Connexion...',
    'auth.resendCode': 'Renvoyer le code',
    'auth.secureSubtitle': 'Connexion sécurisée sans mot de passe',

    // Header
    'header.profile': 'Mon profil',
    'header.settings': 'Paramètres',
    'header.logoutButton': 'Se déconnecter',
    'header.logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',

    // 404 Page
    'notFound.title': '404 - Page introuvable',
    'notFound.description': 'La page que vous cherchez n\'est pas disponible.',
    'notFound.backHome': 'Retour à l\'accueil',

    // Quote Request Page
    'quoteRequest.title': 'Générateur de devis Prévéris',
    'quoteRequest.backToDashboard': 'Retour au tableau de bord',
    'quoteRequest.save': 'Sauvegarder',
    'quoteRequest.loadDraft': 'Charger un brouillon',
    'quoteRequest.step.company': 'Société & Établissement',
    'quoteRequest.step.mainService': 'Prestation principale',
    'quoteRequest.step.calendar': 'Réservation consultation',
    'quoteRequest.step.subServices': 'Sous-prestations',
    'quoteRequest.step.criteria': 'Critères spécifiques',
    'quoteRequest.step.summary': 'Récapitulatif',
    'quoteRequest.step.companyShort': 'Société',
    'quoteRequest.step.mainServiceShort': 'Prestation',
    'quoteRequest.step.calendarShort': 'Calendrier',
    'quoteRequest.step.subServicesShort': 'Sous-prestations',
    'quoteRequest.step.criteriaShort': 'Critères',
    'quoteRequest.step.summaryShort': 'Récap.',
    'quoteRequest.previous': 'Précédent',
    'quoteRequest.next': 'Suivant',
    'quoteRequest.send': 'Envoyer la demande',
    'quoteRequest.sending': 'Envoi...'
  },
  en: {
    // Header
    'search.placeholder': 'Search project, establishment...',
    'notifications': 'Notifications',
    'help': 'Help',
    'logout': 'Logout',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'My projects',
    'nav.companies': 'My companies',
    'nav.newRequest': 'New request',
    'nav.documents': 'My documents',
    'nav.compliance': 'Compliance',
    'nav.mairie': 'City Hall Interface',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.welcome': 'Hello',
    'dashboard.overview': 'Here\'s an overview of your projects and deadlines',
    'dashboard.activeCompany': 'Active company:',
    'dashboard.totalProjects': 'Total projects',
    'dashboard.inProgress': 'In progress',
    'dashboard.completed': 'Completed',
    'dashboard.urgent': 'Urgent',
    'dashboard.recentProjects': 'Recent projects',
    'dashboard.viewAll': 'View all',
    'dashboard.quickActions': 'Quick actions',
    'dashboard.newAT': 'New AT request',
    'dashboard.scheduleAudit': 'Schedule audit',
    'dashboard.complianceTracking': 'Compliance tracking',
    'dashboard.upcomingDeadlines': 'Upcoming deadlines',
    'dashboard.noDeadlines': 'No upcoming deadlines',
    
    // Settings Page
    'settings.title': 'Account Settings',
    'settings.subtitle': 'Manage your personal information and preferences',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.preferences': 'Preferences',
    'settings.companies': 'My Companies',
    'settings.save': 'Save',
    
    // Profile Tab
    'settings.profile.title': 'Personal Information',
    'settings.profile.avatar': 'Profile Picture',
    'settings.profile.avatarFormats': 'Accepted formats: JPG, PNG (max 2MB)',
    'settings.profile.change': 'Change',
    'settings.profile.remove': 'Remove',
    'settings.profile.firstName': 'First Name',
    'settings.profile.lastName': 'Last Name',
    'settings.profile.email': 'Email',
    'settings.profile.phone': 'Phone',
    'settings.profile.position': 'Position',
    'settings.profile.mainCompany': 'Main Company',
    
    // Notifications Tab
    'settings.notifications.title': 'Notification Preferences',
    'settings.notifications.email': 'Email Notifications',
    'settings.notifications.sms': 'SMS Notifications',
    'settings.notifications.whatsapp': 'WhatsApp Notifications',
    'settings.notifications.projectUpdates': 'Project Updates',
    'settings.notifications.deadlines': 'Deadline Reminders',
    'settings.notifications.documents': 'New Documents',
    'settings.notifications.marketing': 'Prévéris News',
    'settings.notifications.urgent': 'Urgent Actions Only',
    'settings.notifications.urgentOnly': 'Urgent Actions',
    
    // Security Tab
    'settings.security.title': 'Security and Privacy',
    'settings.security.authMethod': 'Authentication Method',
    'settings.security.secureLogin': 'Secure Code Login',
    'settings.security.passwordless': 'Your account uses passwordless authentication',
    'settings.security.activeSessions': 'Active Sessions',
    'settings.security.currentSession': 'Current Session',
    'settings.security.lastActivity': 'Last activity',
    'settings.security.now': 'now',
    'settings.security.hoursAgo': '2 hours ago',
    'settings.security.disconnect': 'Disconnect',
    'settings.security.disconnectAll': 'Disconnect all other sessions',
    'settings.security.dataManagement': 'Data Management',
    'settings.security.exportData': 'Export my data',
    'settings.security.dangerZone': 'Danger Zone',
    'settings.security.deleteAccount': 'Delete my account',
    'settings.security.deleteWarning': 'This action is irreversible. All your data will be permanently deleted.',
    'settings.security.active': 'Active',
    'settings.security.current': 'Current',
    
    // Preferences Tab
    'settings.preferences.title': 'Interface Preferences',
    'settings.preferences.language': 'Language',
    'settings.preferences.theme': 'Theme',
    'settings.preferences.timezone': 'Timezone',
    'settings.preferences.dateFormat': 'Date Format',
    'settings.preferences.helpLevel': 'Help Level',
    'settings.preferences.currency': 'Currency',
    'settings.preferences.advanced': 'Advanced Options',
    'settings.preferences.autoSave': 'Auto-save forms',
    'settings.preferences.compactMode': 'Compact mode (more information per page)',
    'settings.preferences.light': 'Light',
    'settings.preferences.dark': 'Dark',
    'settings.preferences.auto': 'Auto',
    'settings.preferences.beginner': 'Beginner (detailed help)',
    'settings.preferences.intermediate': 'Intermediate (standard help)',
    'settings.preferences.expert': 'Expert (minimal help)',
    
    // Companies Tab
    'settings.companies.title': 'Company Access Management',
    'settings.companies.manageAccess': 'Manage Access',
    'settings.companies.administrator': 'Administrator',
    'settings.companies.role': 'Role',
    'settings.companies.accessSince': 'Access since',
    'settings.companies.lastConnection': 'Last connection',
    'settings.companies.today': 'Today',
    'settings.companies.newAccess': 'Access to a new company?',
    'settings.companies.contactAdmin': 'Contact the company administrator or our support team to get access.',
    'settings.companies.requestAccess': 'Request Access',
    
    // Mairie Interface
    'mairie.title': 'City Hall Interface',
    'mairie.subtitle': 'ERP instruction management for your municipality',
    'mairie.activePO': 'Active purchase order',
    'mairie.budgetUsed': 'Budget used',
    'mairie.newPO': 'New purchase order',
    'mairie.depositFiles': 'Submit ERP file for instruction',
    'mairie.dragDrop': 'Drag and drop your files here or click to select',
    'mairie.chooseFiles': 'Choose files',
    'mairie.instructionTracking': 'Instruction tracking',
    'mairie.fileNumber': 'File number',
    'mairie.projectAddress': 'Project address',
    'mairie.status': 'Status',
    'mairie.depositDate': 'Deposit date',
    'mairie.deadline': 'Deadline',
    'mairie.actions': 'Actions',
    'mairie.downloadAdvice': 'Download advice',
    'mairie.requestReview': 'Request review',
    'mairie.filesProcessed': 'Files processed this month',
    'mairie.avgDelay': 'Average instruction delay',
    'mairie.remainingBudget': 'Remaining budget',
    'mairie.days': 'days',
    
    // Status
    'status.complete': 'Complete',
    'status.incomplete': 'Incomplete',
    'status.inProgress': 'In progress',
    'status.inInstruction': 'In instruction',
    'status.validated': 'Validated',
    'status.urgent': 'Urgent',
    'status.finished': 'Finished',
    
    // Companies
    'companies.title': 'My companies',
    'companies.subtitle': 'Manage your companies and establishments',
    'companies.addCompany': 'Add company',
    'companies.selectCompany': 'Select company',
    'companies.establishments': 'Establishments',
    'companies.addEstablishment': 'Add establishment',
    'companies.listView': 'List',
    'companies.mapView': 'Map',
    'companies.siretValidation': '14 digits: 9 SIREN digits + 5 establishment digits',
    'companies.siretValid': 'Valid SIRET',
    'companies.siretInvalid': 'Invalid SIRET',
    'companies.siretChecking': 'Checking...',

    // Auth Page
    'auth.secureTitle': 'Secure Login',
    'auth.emailLabel': 'Email address',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.continue': 'Continue',
    'auth.codeHelp': 'You will receive a temporary login code',
    'auth.methodTitle': 'How would you like to receive your code?',
    'auth.back': 'Back',
    'auth.enterCode': 'Enter your code',
    'auth.codeSentVia': 'Code sent via',
    'auth.codePlaceholder': '123456',
    'auth.login': 'Log in',
    'auth.loading': 'Connecting...',
    'auth.resendCode': 'Resend code',
    'auth.secureSubtitle': 'Passwordless secure login',

    // Header
    'header.profile': 'My profile',
    'header.settings': 'Settings',
    'header.logoutButton': 'Sign out',
    'header.logoutConfirm': 'Are you sure you want to log out?',

    // 404 Page
    'notFound.title': '404 - Page not found',
    'notFound.description': "The page you are looking for isn't available.",
    'notFound.backHome': 'Go back home',

    // Quote Request Page
    'quoteRequest.title': 'Prévéris quote generator',
    'quoteRequest.backToDashboard': 'Back to dashboard',
    'quoteRequest.save': 'Save',
    'quoteRequest.loadDraft': 'Load draft',
    'quoteRequest.step.company': 'Company & establishment',
    'quoteRequest.step.mainService': 'Main service',
    'quoteRequest.step.calendar': 'Consultation booking',
    'quoteRequest.step.subServices': 'Sub-services',
    'quoteRequest.step.criteria': 'Specific criteria',
    'quoteRequest.step.summary': 'Summary',
    'quoteRequest.step.companyShort': 'Company',
    'quoteRequest.step.mainServiceShort': 'Service',
    'quoteRequest.step.calendarShort': 'Calendar',
    'quoteRequest.step.subServicesShort': 'Sub-services',
    'quoteRequest.step.criteriaShort': 'Criteria',
    'quoteRequest.step.summaryShort': 'Summary',
    'quoteRequest.previous': 'Previous',
    'quoteRequest.next': 'Next',
    'quoteRequest.send': 'Submit request',
    'quoteRequest.sending': 'Sending...'
  }
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'fr',
  setLanguage: (lang) => set({ language: lang }),
  t: (key: string) => {
    const { language } = get();
    return translations[language][key] || key;
  }
}));